Repository pairmesh/pairmesh, pull requests merged in 2022-04, with the labels that each got.

#88 Support switch languages in the context menu #83
  i18n/i18n.go
  i18n/locales/en_US.yaml
  i18n/locales/zh_CN.yaml
  node/config/config.go
  node/entry/gui_darwin.go
  node/entry/gui_windows.go
Labels: feature

#96 Support auto detect the default Locale for the first bootstrap #91
  go.mod
  go.sum
  i18n/i18n.go
  node/entry/entry_gui.go
  node/entry/gui_darwin.go
  node/entry/gui_windows.go
Labels: feature

#107 rename the macos pairmesh daemon process name
  app/macos/main.go
  build/macos_dist.sh
Labels: enhancement

#106 docs: add github workflow guide and contributing guide
  CONTRIBUTING.md
  README.md
  docs/guide/dev-guide.md
  docs/guide/github-workflow.md
Labels: documentation, enhancement
