Repository pairmesh/pairmesh, pull requests merged in 2022-03, with the labels that each got.

#42 node: re-implemente the device information menu item
  node/entry/entry_gui.go
  node/entry/systray/systray_darwin.m
Labels: enhancement

#51 add development guidelines to README
  README.md
Labels: documentation, enhancement

#62 add support params to nodes
  node/entry/entry_cli.go
Labels: enhancement, feature

#63 Support dark mode status bar icon on MacOS #56
  .gitignore
  node/.DS_Store
  node/entry/.DS_Store
  node/entry/gui_darwin.go
  node/entry/systray/systray_darwin.go
  node/resources/.DS_Store
Labels: enhancement, feature

#64 release: support Linux arm64
  .github/workflows/release.yml
  Makefile
  build/linux_dist.sh
Labels: feature

#66 add messagebox for better error logging
  internal/messagebox/cocoa/dlg.h
  internal/messagebox/cocoa/dlg.m
  internal/messagebox/cocoa/dlg_darwin.go
  internal/messagebox/mb.go
  internal/messagebox/mb_darwin.go
  internal/messagebox/mb_windows.go
  node/entry/entry_gui.go
Labels: enhancement, feature

#40 tools: add mac application packager
  app/macos/app.m
  app/macos/app_c.go
  app/macos/main.go
  build/macos_dist.sh
  tools/appify/appify
  tools/appify/go.mod
  tools/appify/go.sum
  tools/appify/main.go
Labels: feature

#84 Align current device information and connectivity status to the right side #82
  i18n/locales/zh_CN.yaml
Labels: enhancement
